version: '3.8'

services:
  api-service:
    env_file:
      - .env.prod
    container_name: swp391-skincare-products-sales-system
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://${AZURE_DB_HOST}:3306/${AZURE_DB_NAME}?useSSL=true&requireSSL=false
      - SPRING_DATASOURCE_USERNAME=${AZURE_DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${AZURE_DB_PASSWORD}
      - SPRING_PROFILES_ACTIVE=prod
    restart: always
    depends_on: []