version: '3.8'

services:
  api-service:
    env_file:
      - .env.prod  # Load config từ file môi trường Production
    container_name: swp391-skincare-products-sales-system-api
    build:
      context: .  # Đảm bảo Dockerfile ở thư mục gốc
      dockerfile: Dockerfile  # Cấu hình Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://${AZURE_DB_HOST}:${AZURE_DB_PORT}/${AZURE_DB_NAME}?useSSL=true&requireSSL=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=${AZURE_DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${AZURE_DB_PASSWORD}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
    restart: always
