spring:
  datasource:
    url: "jdbc:mysql://${LOCAL_DB_HOST}:3306/${LOCAL_DB_NAME}"
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update  # Cho phép cập nhật database khi dev
    show-sql: true
#  sql:
#    init:
#      mode: always  # Nếu cần load file `data.sql`