server:
  port: 8080
  servlet:
    context-path: /api/v1/skincare-products-sales-system
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/skincare-products-sales-system"
    username: root
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
