server:
  port: ${PORT:8080}
  servlet:
    context-path: ${CONTEXT_PATH:/api/v1/swp391-skincare-products-sales-system}

spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: update  # Mặc định, từng môi trường có thể ghi đè
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  data:
    redis:
      port: 6379
      host: localhost

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

open:
  api:
    title: API document
    version: v1.0.0
    description: API Service
    serverUrl: http://localhost:8080/api/v1/swp391-skincare-products-sales-system
    serverName: Server
    license: https://github.com/gahoccode215/SWP391_Skincare_Products_Sales_System

jwt:
  signerKey: ${JWT_SIGNER_KEY:1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij}
  valid-duration: ${JWT_VALID_DURATION:3600} # in seconds
  refreshable-duration: ${JWT_REFRESHABLE_DURATION:36000} # in seconds